config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: %i(create destroy)
  resources :home
  resources :posts, only: %i(show)
  resources :comments, only: %i(create)

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, uniqueness: {scope: :provider}

  def self.find_from_auth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"])
  end

  def self.create_from_auth(auth, user = nil)
    user ||= User.create_from_auth!(auth)
    self.create!(
      user: user,
      uid: auth["uid"],
      provider: auth["provider"]
    )
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authorizations
  has_many :posts
  has_many :comments

  def self.create_from_auth!(auth)
    self.create!(
      email: auth["info"]["email"],
      nickname: auth["info"]["name"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
    redirect_to @comment.post
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save

    client = Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.secrets.twitter_consumer_key
      config.consumer_secret = Rails.application.secrets.twitter_consumer_secret
      config.access_token = Rails.application.secrets.twitter_access_token
      config.access_token_secret = Rails.application.secrets.twitter_access_token_secret
    end

    # tweet
    #client.update("@shogo0525 tweet from my app")
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    if auth.present?
      unless @auth = Authorization.find_from_auth(auth)
        @auth = Authorization.create_from_auth(auth)
      end
      log_in(@auth.user)
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.slim
- unless logged_in?
  = link_to 'ログイン', '/auth/twitter'
- else
  = link_to 'ログアウト', logout_path

  = form_with model: Post.new, url: home_index_path do |f|
    = f.text_field :title
    br
    = f.text_area :content
    br
    = f.submit "送信"

ul
- @posts.each do |post|
  li = link_to post.title, post_path(post)

= javascript_pack_tag 'hello_react'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twichie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/show.html.slim
h2 = @post.title

div = simple_format(@post.content)

= form_with model: [ @post, Comment.new ], url: comments_path do |f|
  = f.hidden_field :post_id, value: @post.id
  = f.text_area :content
  br
  = f.submit "送信"


ul
- @comments.each do |comment|
  li
    p
    = comment.user.nickname
    br
    = comment.content